# Generated by Django 6.1.1 on 2026-10-01 13:47

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_repairorder_responded_at_repairorder_responded_ip'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=core.models.attachment_path)),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('repair_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='core.repairorder')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
    ]
