# Generated by Django 6.1.1 on 2026-10-01 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='line_item',
            field=models.ForeignKey(blank=True, help_text='Leave blank for general photos of the vehicle', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachments', to='core.lineitem'),
        ),
    ]
